<?php

namespace OC\BookingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFinder($bookingId){
        $qb = $this->createQueryBuilder('t');

        $qb->where('t.bookingId = :bookingId')
            ->setParameter('bookingId', $bookingId)
            ->orderBy('t.id', 'ASC')
            ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
